version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: sigh123!
      POSTGRES_USER: sigh
      POSTGRES_DB: db
  app:
    image: express-app
    ports:
      - 13000:3000